final currencies = {
  "AED": {
    "symbol": "د.إ",
    "name": "United Arab Emirates Dirham",
    "flag": "TODO"
  },
  "ALL": {
    "symbol": "L",
    "name": "Albanian Lek",
    "flag": "TODO",
  },
  "AMD": {
    "symbol": "֏",
    "name": "Armenian Dram",
    "flag": "TODO",
  },
  "ANG": {
    "symbol": "ƒ",
    "name": "Netherlands Antillean Guilder",
    "flag": "TODO"
  },
  "AOA": {
    "symbol": "Kz",
    "name": "Angolan Kwanza",
    "flag": "TODO",
  },
  "ARS": {
    "symbol": "\$",
    "name": "Argentine Peso",
    "flag": "TODO",
  },
  "AUD": {
    "symbol": "\$",
    "name": "Australian Dollar",
    "flag": "TODO",
  },
  "AZN": {"symbol": "₼", "name": "Azerbaijani Manat", "flag": "TODO"},
  "BBD": {"symbol": "\$", "name": "Barbadian Dollar", "flag": "TODO"},
  "BDT": {"symbol": "৳", "name": "Bangladeshi Taka", "flag": "TODO"},
  "BGN": {"symbol": "‎лв", "name": "Bulgarian Lev", "flag": "TODO"},
  "BHD": {"symbol": ".د.ب", "name": "Bahraini Dinar", "flag": "TODO"},
  "BRL": {"symbol": "R\$", "name": "Brazilian Real", "flag": "TODO"},
  "BSD": {"symbol": "\$", "name": "Bahamian Dollar", "flag": "TODO"},
  "BWP": {"symbol": "P", "name": "Botswanan Pula", "flag": "TODO"},
  "BYN": {"symbol": "Br", "name": "Belarusian Ruble", "flag": "TODO"},
  "CAD": {"symbol": "\$", "name": "Canadian Dollar", "flag": "TODO"},
  "CHF": {"symbol": "Fr.", "name": "Swiss Franc", "flag": "TODO"},
  "CLP": {"symbol": "\$", "name": "Chilean Peso", "flag": "TODO"},
  "CNY": {"symbol": "¥", "name": "Chinese Yuan", "flag": "TODO"},
  "COP": {"symbol": "\$", "name": "Colombian Peso", "flag": "TODO"},
  "CZK": {"symbol": "Kč", "name": "Czech Koruna", "flag": "TODO"},
  "DKK": {"symbol": "kr", "name": "Danish Krone", "flag": "TODO"},
  "DOP": {"symbol": "\$", "name": "Dominican Peso", "flag": "TODO"},
  "EGP": {"symbol": "£", "name": "Egyptian Pound", "flag": "TODO"},
  "ETB": {"symbol": "ብር", "name": "Ethiopian Birr", "flag": "TODO"},
  "EUR": {"symbol": "‎€", "name": "Euro", "flag": "eu"},
  "FJD": {"symbol": "\$", "name": "Fijian Dollar", "flag": "TODO"},
  "GBP": {"symbol": "£", "name": "Pound Sterling", "flag": "TODO"},
  "GEL": {"symbol": "ლ", "name": "Georgian Lari", "flag": "TODO"},
  "GHS": {"symbol": "₵", "name": "Ghanaian Cedi", "flag": "TODO"},
  "GTQ": {"symbol": "Q", "name": "Guatemalan Quetzal", "flag": "TODO"},
  "HKD": {"symbol": "\$", "name": "Hong Kong Dollar", "flag": "TODO"},
  "HNL": {"symbol": "L", "name": "Honduran Lempira", "flag": "TODO"},
  "HRK": {"symbol": "kn", "name": "Croatian Kuna", "flag": "TODO"},
  "HUF": {"symbol": "Ft", "name": "Hungarian Forint", "flag": "TODO"},
  "IDR": {"symbol": "Rp", "name": "Indonesian Rupiah", "flag": "TODO"},
  "ILS": {"symbol": "₪", "name": "Israeli New Shekel", "flag": "TODO"},
  "INR": {"symbol": "₹", "name": "Indian Rupee", "flag": "TODO"},
  "IQD": {"symbol": "ع.د", "name": "Iraqi Dinar", "flag": "TODO"},
  "IRR": {"symbol": "﷼", "name": "Iranian Rial", "flag": "TODO"},
  "ISK": {"symbol": "kr", "name": "Icelandic Króna", "flag": "TODO"},
  "JMD": {"symbol": "\$", "name": "Jamaican Dollar", "flag": "TODO"},
  "JOD": {"symbol": "د.ا", "name": "Jordanian Dinar", "flag": "TODO"},
  "JPY": {"symbol": "¥", "name": "Japanese Yen", "flag": "TODO"},
  "KES": {"symbol": "Ksh", "name": "Kenyan Shilling", "flag": "TODO"},
  "KHR": {"symbol": "៛", "name": "Cambodian Riel", "flag": "TODO"},
  "KRW": {"symbol": "₩", "name": "South Korean Won", "flag": "TODO"},
  "KWD": {"symbol": "د.ك", "name": "Kuwaiti Dinar", "flag": "TODO"},
  "KZT": {"symbol": "₸", "name": "Kazakhstani Tenge", "flag": "TODO"},
  "LAK": {"symbol": "₭", "name": "Laotian Kip", "flag": "TODO"},
  "LBP": {"symbol": "ل.ل", "name": "Lebanese Pound", "flag": "TODO"},
  "LKR": {"symbol": "රු", "name": "Sri Lankan Rupee", "flag": "TODO"},
  "MAD": {"symbol": "DH", "name": "Moroccan Dirham", "flag": "TODO"},
  "MDL": {"symbol": "L", "name": "Moldovan Leu", "flag": "TODO"},
  "MKD": {"symbol": "Ден", "name": "Macedonian Denar", "flag": "TODO"},
  "MMK": {"symbol": "K", "name": "Myanmar Kyat", "flag": "TODO"},
  "MUR": {"symbol": "Rs", "name": "Mauritian Rupee", "flag": "TODO"},
  "MXN": {"symbol": "\$", "name": "Mexican Peso", "flag": "TODO"},
  "MYR": {"symbol": "RM", "name": "Malaysian Ringgit", "flag": "TODO"},
  "NAD": {"symbol": "\$", "name": "Namibian Dollar", "flag": "TODO"},
  "NGN": {"symbol": "₦", "name": "Nigerian Naira", "flag": "TODO"},
  "NOK": {"symbol": "kr", "name": "Norwegian Krone", "flag": "TODO"},
  "NZD": {"symbol": "\$", "name": "New Zealand Dollar", "flag": "TODO"},
  "OMR": {"symbol": "﷼", "name": "Omani Rial", "flag": "TODO"},
  "PAB": {"symbol": "B/.", "name": "Panamanian Balboa", "flag": "TODO"},
  "PEN": {"symbol": "S/", "name": "Peruvian Sol", "flag": "TODO"},
  "PGK": {"symbol": "K", "name": "Papua New Guinean Kina", "flag": "TODO"},
  "PHP": {"symbol": "₱", "name": "Philippine Peso", "flag": "TODO"},
  "PKR": {"symbol": "Rs", "name": "Pakistani Rupee", "flag": "TODO"},
  "PLN": {"symbol": "zł", "name": "Poland złoty", "flag": "TODO"},
  "PYG": {"symbol": "₲", "name": "Paraguayan Guarani", "flag": "TODO"},
  "QAR": {"symbol": "ر.ق", "name": "Qatari Rial", "flag": "TODO"},
  "RON": {"symbol": "lei", "name": "Romanian Leu", "flag": "TODO"},
  "RSD": {"symbol": "din", "name": "Serbian Dinar", "flag": "TODO"},
  "RUB": {"symbol": "‎₽", "name": "Russian Ruble", "flag": "TODO"},
  "SAR": {"symbol": "\$", "name": "Saudi Riyal", "flag": "TODO"},
  "SCR": {"symbol": "SR", "name": "Seychellois Rupee", "flag": "TODO"},
  "SEK": {"symbol": "kr", "name": "Swedish Krona", "flag": "TODO"},
  "SGD": {"symbol": "\$", "name": "Singapore Dollar", "flag": "TODO"},
  "THB": {"symbol": "฿", "name": "Thai Baht", "flag": "TODO"},
  "TJS": {"symbol": "ЅM", "name": "Tajikistani Somoni", "flag": "TODO"},
  "TND": {"symbol": "د.ت", "name": "Tunisian Dinar", "flag": "TODO"},
  "TRY": {"symbol": "₺", "name": "Turkish Lira", "flag": "TODO"},
  "TTD": {"symbol": "\$", "name": "Trinidad & Tobago Dollar", "flag": "TODO"},
  "TWD": {"symbol": "\$", "name": "New Taiwan Dollar", "flag": "TODO"},
  "TZS": {"symbol": "TSh", "name": "Tanzanian Shilling", "flag": "TODO"},
  "UAH": {"symbol": "₴", "name": "Ukrainian Hryvnia", "flag": "TODO"},
  "USD": {"symbol": "\$", "name": "United States Dollar", "flag": "us"},
  "UYU": {"symbol": "\$", "name": "Uruguayan Peso", "flag": "TODO"},
  "UZS": {"symbol": "so'm", "name": "Uzbekistani Som", "flag": "TODO"},
  "VND": {"symbol": "₫", "name": "Vietnamese Dong", "flag": "TODO"},
  "XAF": {
    "symbol": "FCFA",
    "name": "Central African CFA Franc",
    "flag": "TODO"
  },
  "XCD": {"symbol": "\$", "name": "East Caribbean Dollar", "flag": "TODO"},
  "XOF": {"symbol": "CFRA", "name": "West African CFA Franc", "flag": "TODO"},
  "XPF": {"symbol": "₣", "name": "CFP Franc", "flag": "TODO"},
  "ZAR": {"symbol": "R", "name": "South African Rand", "flag": "TODO"},
  "ZMW": {"symbol": "ZK", "name": "Zambian Kwacha", "flag": "TODO"}
};
